[package]
name = "rspack_plugin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rspack_shared = { path="../rspack_shared" }
ast = { package = "swc_ecma_ast" , version = "0.76.0" }
async-trait = "0.1.53"
tokio = { version = "1.17.0", features = ["full"] }
