[package]
edition = "2021"
name    = "rspack_binding_options"
version = "0.1.0"

[features]
default = []
node-api = [
  "dep:napi-derive",
  "dep:napi",
  "dep:napi-sys",
  "dep:rspack_binding_shared",
]

[dependencies]
anyhow = { version = "1", features = ["backtrace"] }
async-trait = "0.1.53"
cfg-if = "1.0.0"
dashmap = "5.0.0"
napi = { features = [
  "async",
  "tokio_rt",
  "serde-json",
  "anyhow",
], optional = true, version = "2" }
napi-derive = { optional = true, version = "2" }
napi-sys = { optional = true, version = "2" }
once_cell = "1"
regex = "1.6.0"
rspack_binding_shared = { path = "../rspack_binding_shared", optional = true }
rspack_core = { path = "../rspack_core" }
rspack_error = { path = "../rspack_error", features = ["napi"] }
rspack_loader_sass = { path = "../rspack_loader_sass" }
rspack_plugin_css = { path = "../rspack_plugin_css" }
rspack_plugin_html = { path = "../rspack_plugin_html" }
rspack_plugin_progress = { path = "../rspack_plugin_progress" }
rspack_plugin_split_chunks = { path = "../rspack_plugin_split_chunks" }
rspack_regex = { path = "../rspack_regex" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
swc_core = { workspace = true, default-features = false, features = [
  "ecma_transforms_react",
] }
# swc_ecma_transforms = { workspace = true, features = [
#   "swc_ecma_transforms_react",
# ] }
tokio   = { workspace = true }
tracing = "0.1.34"
