[workspace]
exclude = [
  "crates/node_binding",
] # Avoid including node binding, since feature unification will cause an linking issue. See: https://doc.rust-lang.org/cargo/reference/features.html#feature-unification
members = ["crates/*", "xtask"]

[profile.dev]
debug       = 2
incremental = true

[profile.release]
codegen-units = 1
debug         = false
incremental   = true
lto           = false
opt-level     = 3


[workspace.dependencies]
swc_core = { version = "0.50.2", default-features = false }
swc_html = { version = "0.97.7" }
swc_html_minifier = { version = "0.94.7" }
tokio = { version = "1.21.0", features = [
  "rt",
  "rt-multi-thread",
  "macros",
  "test-util",
  "parking_lot",
] }

preset_env_base = { version = "0.3.3" }
