[package]
edition    = "2021"
license    = "MIT"
name       = "rspack_plugin_javascript_shared"
repository = "https://github.com/web-infra-dev/rspack"
version    = "0.0.1"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rspack_core = { path = "../rspack_core" }
swc_core    = { workspace = true, features = ["ecma_ast", "ecma_visit", "__common"] }
